name: CI

on:
  push:
    branches:
      - master
    tags-ignore:
      - 'v*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: "Run Tests with JDK ${{ matrix.jdk }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 8,9,11,15 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Install graphviz
        run: sudo apt-get install graphviz

      - name: build and run tests
        run: |
          mvn \
          --batch-mode \
          --no-transfer-progress \
          verify

      - name: archive test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results-${{ matrix.jdk }}
          path: |
            target/it
            target/surefire-reports


  sonar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install graphviz
      run: sudo apt-get install graphviz

    - name: Sonarcloud scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn \
        --batch-mode \
        --no-transfer-progress \
        verify \
        org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
        -Dsonar.projectKey=${{ secrets.SONAR_PROJECTKEY }} \
        -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
        -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}