on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Install graphviz
        run: sudo apt-get install graphviz

      - name: set tag as version
        run: |
          mvn \
          --batch-mode \
          --no-transfer-progress \
          versions:set -DnewVersion=${GITHUB_REF##*/v} \
          versions:commit

      - id: tag_name
        run: |
          echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}

      - name: deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        run: |
          mvn \
          --batch-mode \
          --no-transfer-progress \
          clean deploy -P deploy-to-sonatype

      - name: create Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "CHANGELOG.md"
          ALLOW_EMPTY_CHANGELOG: "false"
          ALLOW_TAG_PREFIX: "true"
          RELEASE_NAME_PREFIX: "Release: "
        with:
          args: |
            ./target/asciidoctorj-liquibase-extension.jar
            ./target/asciidoctorj-liquibase-extension-javadoc.jar
            ./target/asciidoctorj-liquibase-extension-sources.jar

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Announcement
        uses: yuzutech/zulip-send-message-action@v0.1.0
        with:
          username: ${{ secrets.ZULIP_USERNAME }}
          api-key: ${{ secrets.ZULIP_API_KEY }}
          organization-url: 'https://asciidoctor.zulipchat.com'
          to: '279652'
          type: 'stream'
          topic: 'contrib releases'
          content: |
            asciidoctorj-liquibase-extension [${{ env.RELEASE_VERSION }}](https://github.com/uniqueck/asciidoctorj-liquibase-extension/releases/tag/${{ env.RELEASE_VERSION }}) is out!